"""upgradeDone

Revision ID: 5b0bd4d641e9
Revises: f22e5256ade4
Create Date: 2023-05-13 21:46:33.474460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0bd4d641e9'
down_revision = 'f22e5256ade4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseactivation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('coord', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courseactivation')
    # ### end Alembic commands ###
