"""update

Revision ID: 8fc244b7f601
Revises: ef6201efbe72
Create Date: 2023-05-13 21:29:07.332022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc244b7f601'
down_revision = 'ef6201efbe72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentmanagement',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentmanagement')
    # ### end Alembic commands ###
