"""upgradeDone

Revision ID: a21d340ec0d3
Revises: 5b0bd4d641e9
Create Date: 2023-05-14 16:38:05.056696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21d340ec0d3'
down_revision = '5b0bd4d641e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
