"""upgradeDone

Revision ID: b950c069b8fb
Revises: d0a26e5754f6
Create Date: 2023-05-14 16:47:15.024758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b950c069b8fb'
down_revision = 'd0a26e5754f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faceencoding',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('face_encoding', sa.String(length=6000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faceencoding')
    # ### end Alembic commands ###
