"""upgradeDone

Revision ID: d0a26e5754f6
Revises: a21d340ec0d3
Create Date: 2023-05-14 16:41:49.550458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a26e5754f6'
down_revision = 'a21d340ec0d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faceencoding',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.String(length=1000), nullable=False),
    sa.Column('face_encoding', sa.String(length=10000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faceencoding')
    # ### end Alembic commands ###
