"""update

Revision ID: ed3f676b54e5
Revises: b900d1369a89
Create Date: 2023-05-14 21:11:28.909319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3f676b54e5'
down_revision = 'b900d1369a89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseactivation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('coord', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faceencoding',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('face_encoding', sa.String(length=10000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentmanagement',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentmanagement')
    op.drop_table('faceencoding')
    op.drop_table('courseactivation')
    # ### end Alembic commands ###
