"""update

Revision ID: ef6201efbe72
Revises: f22e5256ade4
Create Date: 2023-05-13 21:28:20.314301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef6201efbe72'
down_revision = 'f22e5256ade4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentmanagement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentmanagement',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('course_id', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
