"""create table

Revision ID: f22e5256ade4
Revises: 
Create Date: 2023-05-13 16:26:20.062902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22e5256ade4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faceencoding',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('face_encoding', sa.BINARY(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentmanagement',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentmanagement')
    op.drop_table('faceencoding')
    # ### end Alembic commands ###
