"""update

Revision ID: fef6480af31d
Revises: ed3f676b54e5
Create Date: 2023-05-15 16:10:22.257912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef6480af31d'
down_revision = 'ed3f676b54e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courseactivation', ['course_id'])
    op.create_unique_constraint(None, 'faceencoding', ['student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faceencoding', type_='unique')
    op.drop_constraint(None, 'courseactivation', type_='unique')
    # ### end Alembic commands ###
